jobs:
  include:
  - stage: macOS
    os: osx
    osx_image: xcode13.3
    before_script:
      - brew install stow
      - python3 -m venv venv && source venv/bin/activate
      - pip3 install ansible
      - pip3 install ansible-lint
    script:
      - echo "Running on macOS"
      - ansible-playbook playbook.yml -vvv --tags mac
      - ./install

  - stage: Linux
    os: linux
    dist: focal
    before_install:
      - sudo apt-get install stow
    script:
      - echo "Running on Linux"
      - ./install
