#!/bin/bash

# Determine the operating system
readonly OS=$(uname)
readonly PWD=$(pwd)

if [[ "${OS}" == "Darwin" ]]; then
    echo "Running on (macOS)"
    STOW_DIRS="alacritty, nvim, ranger, skhd, tmux, yabai, zsh, fish"
    DOTFILES="${PWD}/mac"
else
    echo "Running on (Linux)"
    STOW_DIRS="alacritty, bash, compton, fish, i3, nvim, ranger, tmux, Xresources"
    DOTFILES="${PWD}/linux"
fi

IFS=',' read -ra DIRS <<< "${STOW_DIRS}"
for i in "${DIRS[@]}"; do
    stow --verbose --restow --dotfiles --dir=${DOTFILES} --target=${HOME} ${i}
done
