- name: Install packages
  import_tasks: installs.yml
  tags:
    - linux

- name: Download dotfiles
  import_tasks: dotfiles.yml
  tags:
    - linux
    - dotfiles

# TODO: Install nodejs/npm latest version 18
#
# TODO: Install oh-my-fish
