- name: Hide icons from desktop
  ansible.builtin.shell: defaults write com.apple.finder CreateDesktop false; killall Finder

- name: Install oh-my-zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
